Update api check logic“

diff --git a/.github/workflows/apichecks.yml b/.github/workflows/apichecks.yml
--- a/.github/workflows/apichecks.yml
+++ b/.github/workflows/apichecks.yml
@@ -48,13 +48,28 @@ jobs:
           name: export-api-log
           path: ./export-api.log
       - name: Check for API Changes
-        id: api-check
+        id: api-check-diff
         run: |
           git status
           git diff --exit-code api/
         shell: bash
         continue-on-error: true
-      # Add check-label step after api-check
+      - name: Echo for API label
+        if: steps.api-check-diff.outcome == 'failure'
+        run: |
+          echo "API changes detected."
+          echo "Please run powershell -ExecutionPolicy Bypass -File .\eng\Export-API.ps1 to update the API files"
+          exit 1
+        shell: bash
+      - name: Check if 'api/' folder has changes
+        id: api-check
+        run: |
+          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^api/'; then
+            echo "Changes detected in the 'api/' folder. Marking the step as failure."
+            exit 1
+          fi
+        shell: bash
+        continue-on-error: true
       - name: Check for special label
         id: check_label
         if: steps.api-check.outcome == 'failure' && contains(github.event.pull_request.labels.*.name, 'api-breaking-change-signoff') # Run only if the api-check step failed
